# Generated by Django 6.0.2 on 2026-06-25 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helloworld',
            name='code',
            field=models.CharField(verbose_name='読み仮名'),
        ),
        migrations.AlterField(
            model_name='helloworld',
            name='description',
            field=models.TextField(verbose_name='語釈'),
        ),
    ]
