# Generated by Django 6.0.2 on 2026-06-25 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0002_alter_helloworld_code_alter_helloworld_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='helloworld',
            name='click_count',
            field=models.PositiveIntegerField(default=0, verbose_name='クリック数'),
        ),
    ]
